### ISSUE TITLE
NGIAB ngen-deps fails to build while running ngen-datastream

### ISSUE THREAD

**Issue by arpita0911patel** [CIROH-UA/NGIAB-CloudInfra#154]
While trying to run ngen-datastream on AWS (t4g.xlarge instance , 100GB EBS vol) seeing below error:

## Current behavior
Seeing error while trying to run ngen-datastream and looks like it is failing to build ngen-deps image.

## Steps to replicate behavior (include URLs)

1. Steps as per https://github.com/CIROH-UA/ngen-datastream/blob/main/INSTALL.md
2. Failed at step # 3 Run the docker builds script
3. [ec2-user@ip-172-31-18-181 scripts]$ ./install.sh

4. Error:
![image](https://github.com/CIROH-UA/NGIAB-CloudInfra/assets/54657/f4c3b3f4-29f7-49d0-b942-a6c1dfb687f1)

**Comment by arpita0911patel** [comment]
@benlee0423 , this could be related to the error seeing here:
https://github.com/CIROH-UA/NGIAB-CloudInfra/actions/runs/8849599367/job/24302703942

640.7 ERROR: Package 'blosc2' requires a different Python: 3.9.18 not in '<4,>=3.10'

**Comment by benlee0423** [comment]
@arpita0911patel 
This error is due to python version.
In rocky-linux 9.x, default python version is 3.9, and blosc2 requires >= 3.10.
Some [discussion](https://forums.rockylinux.org/t/installing-python-packages-for-python-3-11-on-rocky-linux-9-3-blue-onyx/13447/4) does not recommend to change default python version in rocky-linux because it will break some other system libraries.
We have not make any changes related to this, and why it breaks now is uncertain.
